### ISSUE TITLE
curtsies.formatstring.parse fails with ValueError

### ISSUE THREAD

**Issue by sebastinas** [thomasballinger/curtsies#76]
See https://github.com/bpython/bpython/issues/545.

```py
>>> from curtsies.formatstring import parse
>>> parse("\033[6;3HHello")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebastian/development/curtsies/curtsies/escseqparse.py", line 27, in parse
    front, token, rest = peel_off_esc_code(rest)
  File "/home/sebastian/development/curtsies/curtsies/escseqparse.py", line 69, in peel_off_esc_code
    d['numbers'] = [int(x) for x in d['numbers'].split()]
  File "/home/sebastian/development/curtsies/curtsies/escseqparse.py", line 69, in <listcomp>
    d['numbers'] = [int(x) for x in d['numbers'].split()]
ValueError: invalid literal for int() with base 10: '6;3'
```

I'm not sure what's the best way to handle this. Having it not fail would be nice. A specific exception if parsing fails that we could catch in bpython could be another way.

**Comment by sebastinas** [comment]
With #77 merged, the next step seems to be to handle `info['command'] = 'H'` in `token_type`:

```diff
@@ -83,6 +83,9 @@ def token_type(info):
         if value == RESET_ALL: return dict(dict((k, None) for k in STYLES), **{'fg':None, 'bg':None})
         if value == RESET_FG: return {'fg':None}
         if value == RESET_BG: return {'bg':None}
+    if info['command'] == 'H':
+        # TODO implement proper handling
+        return {}
     raise ValueError("Can't parse escape seq %r" % info)
 
 if __name__ == '__main__':
```

**Comment by thomasballinger** [comment]
https://github.com/thomasballinger/curtsies/commit/6a9e41947020f0da48084b9b3e4a0ba3883d52cc introduces a pretty weak fix, the long term fix is to use the escape sequences parsing in [Blessed](https://github.com/jquast/blessed/) instead.
