### ISSUE TITLE
Tests have been failing for a long time

### ISSUE THREAD

**Issue by thomasballinger** [thomasballinger/curtsies#89]
https://travis-ci.org/thomasballinger/curtsies/builds/132383330

I figured I documented this somewhere but don't see anything :(

**Comment by thomasballinger** [comment]
They work fine locally, it's a Travis CI thing. I'm guessing that the `sys.stdin.isatty` used to be false for Travis, but now it's true.

**Comment by thomasballinger** [comment]
Whoops, that was something else. Maybe should separately detect Travis for now.

**Comment by thomasballinger** [comment]
Here's the log for posterity in case Travis deletes logs. I'm going to skip these tests on Travis because I don't want to mess around with however their weird stdin works.

~~~
0.40s$ nosetests tests
............................S...................................................EEEE..SSSSS
======================================================================
ERROR: test_cursor_position (test_terminal.TestCursorAwareWindow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/thomasballinger/curtsies/tests/test_terminal.py", line 145, in test_cursor_position
    with self.window:
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 255, in __enter__
    self.top_usable_row, _ = self.get_cursor_position()
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 298, in get_cursor_position
    c = retrying_read()
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 288, in retrying_read
    (resp,))
ValueError: (u"Stream should be blocking - should't return ''. Returned %r so far", (u'',))
-------------------- >> begin captured stdout << ---------------------
REPORT_DEVICE_STATUS 6 
--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
curtsies.window: DEBUG: -------initializing Window object <curtsies.window.CursorAwareWindow object at 0x7f45f1c746d0>------
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: test_inital_cursor_position (test_terminal.TestCursorAwareWindow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/thomasballinger/curtsies/tests/test_terminal.py", line 152, in test_inital_cursor_position
    with self.window:
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 255, in __enter__
    self.top_usable_row, _ = self.get_cursor_position()
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 298, in get_cursor_position
    c = retrying_read()
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 288, in retrying_read
    (resp,))
ValueError: (u"Stream should be blocking - should't return ''. Returned %r so far", (u'',))
-------------------- >> begin captured stdout << ---------------------
REPORT_DEVICE_STATUS 6 
--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
curtsies.window: DEBUG: -------initializing Window object <curtsies.window.CursorAwareWindow object at 0x7f45f1c85490>------
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: test_render (test_terminal.TestCursorAwareWindow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/thomasballinger/curtsies/tests/test_terminal.py", line 139, in test_render
    with self.window:
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 255, in __enter__
    self.top_usable_row, _ = self.get_cursor_position()
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 298, in get_cursor_position
    c = retrying_read()
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 288, in retrying_read
    (resp,))
ValueError: (u"Stream should be blocking - should't return ''. Returned %r so far", (u'',))
-------------------- >> begin captured stdout << ---------------------
REPORT_DEVICE_STATUS 6 
--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
curtsies.window: DEBUG: -------initializing Window object <curtsies.window.CursorAwareWindow object at 0x7f45f1c85690>------
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: test_report_extra_bytes (test_terminal.TestCursorAwareWindowWithExtraInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/thomasballinger/curtsies/tests/test_terminal.py", line 178, in test_report_extra_bytes
    with self.window:
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 255, in __enter__
    self.top_usable_row, _ = self.get_cursor_position()
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 298, in get_cursor_position
    c = retrying_read()
  File "/home/travis/build/thomasballinger/curtsies/curtsies/window.py", line 288, in retrying_read
    (resp,))
ValueError: (u"Stream should be blocking - should't return ''. Returned %r so far", (u'',))
-------------------- >> begin captured stdout << ---------------------
REPORT_DEVICE_STATUS 6 
--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
curtsies.window: DEBUG: -------initializing Window object <curtsies.window.CursorAwareWindow object at 0x7f45f1c85890>------
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
Ran 91 tests in 0.217s
FAILED (SKIP=6, errors=4)
~~~

**Comment by jquast** [comment]
I might suggest to add a script like this into your test pipeline to provide such confidence about travis' terminal state, https://github.com/jquast/blessed/blob/master/bin/display-terminalinfo.py

**Comment by thomasballinger** [comment]
Oh sweet, thanks for the pointer.
