### ISSUE TITLE
Support F3 on my platform

### ISSUE THREAD

**Issue by cool-RR** [thomasballinger/curtsies#99]
```
[root@tommy ~]# python -m curtsies.events                                   
press a bunch of keys (not at the same time, but you can hit them pretty quickly)     
---                                                                                   
'\x1b[[C'                                                                             
unknown!!!                                                                            
Unidentified character sequence!                                                      
type 'ok' to prove you're not pounding keys                                           
type 'ok' to prove you're not pounding keys ok                                        
Press the key that produced '\x1b[[C' again please                                    
Describe in English what key you pressed: F3                                          
Thanks! Please open an issue at https://github.com/thomasballinger/curtsies/issues    
or email thomasballinger@gmail.com. Include this terminal history or keylog.txt.      
You can keep pressing keys                                                            
Traceback (most recent call last):                                                    
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main              
    "__main__", fname, loader, pkg_name)                                              
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code                         
    exec code in run_globals                                                          
  File "/usr/lib/python2.6/site-packages/curtsies/events.py", line 312, in <module>   
    try_keys()                                                                        
  File "/usr/lib/python2.6/site-packages/curtsies/events.py", line 298, in try_keys   
    chars = os.read(sys.stdin.fileno(), 1000)                                         
KeyboardInterrupt                                                                     
```

**Comment by thomasballinger** [comment]
Great, just merged this. If you've got a moment, would you mind submitting all your F keys? If this is for bpython, I want to make sure you have my favorite, F7!

**Comment by cool-RR** [comment]
Thanks!

'\x1b[[A' is called F1
'\x1b[[B' is called F2
'\x1b[[C' is called F3
'\x1b[[E' is called F5
'\x1b[[D' is called F4

The rest were recognized.

**Comment by thomasballinger** [comment]
Thanks!
